[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 9600
lib_ldf_mode = deep+
build_flags =
    -D DEBUG_PRINT=Serial

lib_deps =
    https://github.com/wollewald/INA226_WE.git
    https://github.com/Seeed-Studio/Grove_Digital_Light_Sensor.git
    https://github.com/Sensirion/arduino-i2c-scd4x.git
    https://github.com/Seeed-Studio/Multi_Channel_Relay_Arduino_Library.git
    olikraus/U8g2
    paulstoffregen/OneWire
    milesburton/DallasTemperature
    bogde/HX711
